package ru.wkn.report;

/**
 * The class {@code AnalyticalInformationGenerator} represents an analytical information generator based on
 * questionnaire survey results statistics. An analytical information is generated by means specific analytical
 * algorithms.
 *
 * @author Orin Adraas
 */
// TODO: implement this class for the analytical information generating
@SuppressWarnings(value = {"unused"})
public class AnalyticalInformationGenerator {
}
